---
title: "Lab2_Esther"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(dplyr)
library(GGally)
```

```{r read}
#read in dataset
drive <- read.csv("./data/bad-drivers.csv") 
head(drive)
#rename the cols 
drive <- drive %>% rename(amt_per_bil_miles = Number.of.drivers.involved.in.fatal.collisions.per.billion.miles, 
                          pct_speeding = Percentage.Of.Drivers.Involved.In.Fatal.Collisions.Who.Were.Speeding, 
                          pct_alcohol_impaired = Percentage.Of.Drivers.Involved.In.Fatal.Collisions.Who.Were.Alcohol.Impaired, 
                          pct_not_distracted = Percentage.Of.Drivers.Involved.In.Fatal.Collisions.Who.Were.Not.Distracted, 
                          pct_no_previous = Percentage.Of.Drivers.Involved.In.Fatal.Collisions.Who.Had.Not.Been.Involved.In.Any.Previous.Accidents, 
                          premiums = Car.Insurance.Premiums...., 
                          losses = Losses.incurred.by.insurance.companies.for.collisions.per.insured.driver....)
colnames(drive)
```

```{r eda}
#draftsmans plot
pairs(drive, gap = 0)
#histogram
ggplot(drive, aes(x = pct_speeding)) +
  geom_histogram(bins = 15)
```
Premiums and losses have a positive relationship. 
```{r regression}
#Simple
reg01 <- lm(premiums ~ pct_no_previous, drive)
summary(reg01)
#Multiple
reg02 <- lm(premiums ~ pct_no_previous + amt_per_bil_miles + pct_speeding, drive)
summary(reg02)
#Polynomial
reg03 <- lm(premiums ~ poly(pct_no_previous, 2, raw=TRUE), drive)
summary(reg03)
#plot
ggplot(drive, aes(x = pct_no_previous, y = premiums)) +
  geom_point() +
  stat_smooth(method='lm', formula = y~poly(x,2))
```


```{r training}
rows <- sample(1:51, 10)

test <- drive[rows,]
train <- drive[-rows,]

#Simple
reg01 <- lm(premiums ~ pct_no_previous, train)
summary(reg01)
#Multiple
reg02 <- lm(premiums ~ pct_no_previous + amt_per_bil_miles + pct_speeding, train)
summary(reg02)
#Polynomial
reg03 <- lm(premiums ~ poly(pct_no_previous, 2, raw=TRUE), train)
summary(reg03)

```


```{r test}

test$predict01 <- predict(reg01, test)
test$resid01 <- test$premiums - test$predict01
  
test$predict02 <- predict(reg02, test)
test$resid02 <- test$premiums - test$predict02

test$predict03 <- predict(reg03, test)
test$resid03 <- test$premiums - test$predict03

mse_01 <- mean((test$resid01)^2)
mse_02 <- mean((test$resid02)^2)
mse_03 <- mean((test$resid03)^2)

```

```{r cross val}

# Number of observations
N <- nrow(drive)
# Number of desired splits
folds <- 5

# Generate indices of holdout observations
cross <- split(sample(1:N), 1:folds)

#df
crossValResults <- data.frame(3,5)

```

